noticias:
    path:     /noticias.html
    defaults: { _controller: "AppBundle:Default:articleList" }

noticias_page:
    path:     /{page}/noticias.html
    defaults: { _controller: "AppBundle:Default:articleListPager" }
    
show_noticia:
    path:     /noticia/{slug}.html
    defaults: { _controller: "AppBundle:Default:article" }
    
contacto:
    path:     /contacto.html
    defaults: { _controller: "AppBundle:Default:contacto" }

contact_send:
    path:     /contacto-send.html
    defaults: { _controller: "AppBundle:Default:contactoSend" }

about:
    path:     /acerca.html
    defaults: { _controller: "AppBundle:Default:about" }

prototipo:
    path:     /prototipo.html
    defaults: { _controller: "AppBundle:Default:prototipo" }

estaciones:
    path:     /estaciones.html
    defaults: { _controller: "AppBundle:Default:estaciones" }

download_document:
    path:     /{id}/descargar-archivo
    defaults: { _controller: "AppBundle:Default:downloadOriginalFile" }

retrieve_video:
    path:     /{estacionId}/video
    defaults: { _controller: "AppBundle:Default:retrieveVideo" }
    

site_images:
    path:     /imagenes.html
    defaults: { _controller: "AppBundle:Default:images" }    