noticias:
    path:     /noticias.html
    defaults: { _controller: "AppBundle:Default:articleList" }

noticias_page:
    path:     /{page}/noticias.html
    defaults: { _controller: "AppBundle:Default:articleListPager" }
    
show_noticia:
    path:     /noticia/{slug}.html
    defaults: { _controller: "AppBundle:Default:article" }
    
contacto:
    path:     /contacto.html
    defaults: { _controller: "AppBundle:Default:contacto" }

contact_send:
    path:     /contacto-send.html
    defaults: { _controller: "AppBundle:Default:contactoSend" }

about:
    path:     /acerca.html
    defaults: { _controller: "AppBundle:Default:about" }

prototipo:
    path:     /prototipo.html
    defaults: { _controller: "AppBundle:Default:prototipo" }

estaciones:
    path:     /estaciones.html
    defaults: { _controller: "AppBundle:Default:estaciones" }

download_document:
    path:     /{id}/descargar-archivo
    defaults: { _controller: "AppBundle:Default:downloadOriginalFile" }

retrieve_video:
    path:     /{estacionId}/video
    defaults: { _controller: "AppBundle:Default:retrieveVideo" }
    

proyecto-imagenes:
    path:     /proyecto/imagenes.html
    defaults: { _controller: "AppBundle:Default:proyectoImages" }

proyecto-estacion:
    path:     /proyecto/{estacionId}/estacion.html
    defaults: { _controller: "AppBundle:Default:proyectoEstacion" }

download-estacion-image-pack:
    path:     /proyecto/{estacionId}/descargar
    defaults: { _controller: "AppBundle:Default:proyectoEstacionDescargarImagenes" }

download-estacion-files:
    path:     /proyecto/{estacionId}/file/descargar
    defaults: { _controller: "AppBundle:Default:proyectoEstacionDescargarArchivo" }
    
site_images:
    path:     /imagenes.html
    defaults: { _controller: "AppBundle:Default:images" }    
    
sendnewsletter:
    path:     /send-newsletter
    defaults: { _controller: "AppBundle:Default:saveNewsletter" }    
    methods:  POST